---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: workload
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/AmrFawzymoh/workload.git
  secretRef:
    name: workload-auth  

